---
- name: Apt install nice to haves
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - vim
    - tmux
    - curl

- name: Apt install network tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    # open ssh
    - openssh-server
    - openssh-client

    # fast, parallel, modular, login brute-forcer for network services
    - medusa 

    # NET-3 networking toolkit
    - net-tools 

    # various deps? 
    - libssl-dev
    - libffi-dev
    - build-essential

- include: crackmapexec.yml

- include: shell.yml

- include: nmap.yml

- include: metasploit.yml
