---
- name: Apt install metasplot deps
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - git 
    - autoconf 
    - build-essential 
    - libpcap-dev 
    - libpq-dev 
    - zlib1g-dev 
    - libsqlite3-dev

- name: Mkdir $HOME/src/
  file: 
    state: directory
    path: "{{ ansible_env.HOME }}/src/" # usually /root/src/

- name: Git checkout metasploit source
  git:
    repo: https://github.com/rapid7/metasploit-framework.git
    dest: "{{ ansible_env.HOME }}/src/metasploit-framework"
    update: no
    #version: 
