---
- hosts: all
  become: False
  roles: 
    - role: marksamuli.pyenv
      tags:
        - pyenv
        - python

    - role: senorsmile.pipenv
      #pipenv_user: 'vagrant'
      tags:
        - pipenv
        - python

    - role: zzet.rbenv
      rbenv:
        env: system
        version: v1.0.0
        default_ruby: 2.6.5
        rubies:
          - version: 2.6.5
      tags:
        - rbenv
        - ruby

    #- role: zzet.rbenv
    #  rbenv_users:
    #    - vagrant
    #  rbenv:
    #    #env: system
    #    env: user
    #    version: v1.0.0
    #    #default_ruby: 2.4.2
    #    default_ruby: 2.6.5
    #    rubies:
    #      #- version: 2.4.2
    #      - version: 2.6.5
    #  tags:
    #    - rbenv
    #    - ruby

- hosts: all
  become: True
  roles: 
    - role: art_pentesting
      art_pentesting_shell: False

    - role: metasploit


