---
- name: Apt install metasplot deps
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - git 
    - autoconf 
    - build-essential 
    - libpcap-dev 
    - libpq-dev 
    - zlib1g-dev 
    - libsqlite3-dev

    - gpgv2
    - bison
    - curl
    - git-core
    - libapr1
    - libaprutil1
    - libcurl4-openssl-dev
    - libgmp3-dev
    #- libpcap-dev
    #- libpq-dev
    - libreadline6-dev
    #- libsqlite3-dev
    - libssl-dev
    - libsvn1
    - libtool
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - locate
    - ncurses-dev
    - openssl
    - postgresql
    - postgresql-contrib
    - wget
    - xsel
    - zlib1g
    #- zlib1g-dev

- name: Mkdir $HOME/src/
  file: 
    state: directory
    path: "{{ ansible_env.HOME }}/src/" # usually /root/src/

- name: Git checkout metasploit source
  git:
    repo: https://github.com/rapid7/metasploit-framework.git
    dest: "{{ ansible_env.HOME }}/src/metasploit-framework"
    update: no
    #version: 

- name: Ruby bundle gems
  bundler:
    state: present
    gemfile: "{{ ansible_env.HOME }}/src/metasploit-framework"
    executable: /usr/local/rbenv/shims/bundle
